apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-fuchicorp-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 2000m
    nginx.org/client-max-body-size: 2000m
  name: fuchicorp-docker-ingress
spec:
  rules:
  - host: docker.fuchicorp.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nexus-fuchicorp-service
          servicePort: {{ .Values.nexusport }}
      - path: /v2/
        backend:
          serviceName: nexus-fuchicorp-service
          servicePort: {{ .Values.repo_port }}
  tls:
  - hosts:
    - docker.fuchicorp.com
    secretName: tls-docker-prod-cert
