apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fuchicorp-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-fuchicorp-prod

spec:
  rules:

  - host: grafana.fuchicorp.com
    http:
      paths:
      - backend:
          serviceName: grafana-fuchicorp-service
          servicePort: {{ .Values.grafanaport }}

  - host: jenkins.fuchicorp.com
    http:
      paths:
      - backend:
          serviceName: jenkins-fuchicorp-service
          servicePort: {{ .Values.jenkinsport }}

  - host: jira.fuchicorp.com
    http:
      paths:
      - backend:
          serviceName: jira-fuchicorp-service
          servicePort: {{ .Values.jiraport }}

  - host: nexus.fuchicorp.com
    http:
      paths:
      - backend:
          serviceName: nexus-fuchicorp-service
          servicePort: {{ .Values.nexusport }}

  - host: vault.fuchicorp.com
    http:
      paths:
      - backend:
          serviceName: vault-fuchicorp-service
          servicePort: {{ .Values.vaultport }}
  tls:
  - hosts:
    - vault.fuchicorp.com
    - nexus.fuchicorp.com
    - jira.fuchicorp.com
    - grafana.fuchicorp.com
    - jenkins.fuchicorp.com
    secretName: tls-prod-cert
