apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-fuchicorp-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 2000m
    nginx.org/client-max-body-size: 2000m
    kubernetes.io/tls-acme: “true”
  name: fuchicorp-docker-ingress
spec:
  rules:
  - host: docker.fuchicorp.com
    http:
      paths:
      - backend:
          serviceName: nexus-fuchicorp-service
          servicePort: {{ .Values.repo_port }}
  tls:
  - hosts:
    - docker.fuchicorp.com
    secretName: tls-docker-prod-cert
